services:
  - rabbitmq

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

language: node_js

compiler:
  - gcc

before_install:
  - export CXX="g++-4.8"

node_js:
  - "0.12.7"
