language: node_js
node_js:
- 8.15.1
services:
- rabbitmq
- memcached
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - rabbitmq-server
cache:
  directories:
  - node_modules
before_install:
- export CXX="g++-4.8"
deploy:
  provider: npm
  email: cloudservices@loyalty.co.nz
  api_key:
    secure: loNgec3LpO0fr9AJTbzaawzCAJauscSu+jvGeIakM3J8sILRGfIWj0VZlXKN0fiLXYm2eHQatfkzS2QH/6D0BN1fn/4O6jlVhQJDhNKVK1vjBEkVzm1iwQHq9Flm4JA9GjHpBxrNAlh23nSnCug7xKNY+oGRvmW9BHgTYB8P2sqqu3NBFmUHPpF3vWVTCaG9qECg1YFoa2I0tJpcNH5+MUUat3mf7vRaE81WmH/cHITDqkizyn4ts+gdXzzs9xG0eukp/NCfei3fOSeI3kD4mubkOXt5SUVtXDu4GeBfNxziMom3+H+cSI9BUCcNZg62AH/ERgXmINMinJtQNSITgYikc/eSraRFXb0LKwt9s+voWal7mIwxcDDxfvoyoIeI6cqU0Q1v8CV6xS3pJsiE6TjkyTi3y/n9aZEwzzDuviUFQTihOnAb+E7iJ9+WDbb93q3nTMW7KX4EunnL3pPGsvZ5ABmIecRp22YClaxybCMmXpPWQXcVJfviYMDlkarMwCLGWkrb71Ec/SsnD8f4IwoXIbOqshlQPwwPmQoRwzxbp7/BHIh6z1ZVAGHfA+7WDYcgexXOyGQo7pLIn5Bm8uIQC9RfXoI0Bke837JtyQkyyf/51T4Mi5eiaYLvAT1rilZukvSHEyfcroUd4ZPQr5sPmB97mhwHvStTN31c3o8=
  on:
    tags: true
